# Generated by Django 5.0.7 on 2024-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_categoria_presupuesto_detallegasto_delete_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallegasto',
            name='tipo_gasto',
            field=models.CharField(blank=True, choices=[('fijo', 'Fijo'), ('fantasma', 'Fantasma')], max_length=100, null=True),
        ),
    ]
