# Generated by Django 5.0.7 on 2024-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_remove_presupuesto_tipo_detallegasto_tipo_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegasto',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallegasto',
            name='tiene_fecha_limite',
            field=models.BooleanField(default=False),
        ),
    ]
