# Generated by Django 5.0.7 on 2024-07-28 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('age', models.IntegerField(default=18, null=True)),
                ('profession', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('work', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_email', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
